# Generated by Django 5.2.5 on 2025-09-01 03:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0002_checklist_kpi_checklistitem_bonusrule_task_comment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualKpiEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date the event occurred.",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="The value of the entry, e.g., '1' for one error.",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context or comments."
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        help_text="The KPI this entry is for, e.g., 'Calidad Administrativa'.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.kpi",
                    ),
                ),
            ],
        ),
    ]
