# Generated by Django 5.2.5 on 2025-09-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_manualkpientry"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi",
            name="is_warning_kpi",
            field=models.BooleanField(
                default=False,
                help_text="Check if this KPI represents a disciplinary warning that should trigger an email.",
            ),
        ),
    ]
