# Generated by Django 5.2.6 on 2025-09-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_task_completed_by_manager_task_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default Settings", max_length=255, unique=True
                    ),
                ),
                (
                    "calculation_basis",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("weekly", "Weekly"),
                            ("daily", "Daily"),
                        ],
                        default="monthly",
                        help_text="The basis for salary calculation (e.g., monthly, weekly, or daily hours).",
                        max_length=10,
                    ),
                ),
                (
                    "base_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=160.0,
                        help_text="The number of base hours corresponding to the selected calculation basis.",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]
