# Generated by Django 5.2.6 on 2025-09-07 17:53

from django.db import migrations

def create_default_settings(apps, schema_editor):
    CompanySettings = apps.get_model('employees', 'CompanySettings')
    # The load() method in the model handles the creation with pk=1
    CompanySettings.objects.get_or_create(
        pk=1,
        defaults={
            'name': 'Default Settings',
            'calculation_basis': 'monthly',
            'base_hours': 160.00
        }
    )

def delete_default_settings(apps, schema_editor):
    CompanySettings = apps.get_model('employees', 'CompanySettings')
    CompanySettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_companysettings"),
    ]

    operations = [
        migrations.RunPython(create_default_settings, delete_default_settings),
    ]
