# Generated by Django 5.2.6 on 2025-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_populate_company_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
