# Generated by Django 5.2.6 on 2025-09-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_task_parent_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="measurement_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("count_lt", "Count (Less Than)"),
                    ("count_gt", "Count (Greater Than)"),
                    ("composite_ipac", "Composite IPAC"),
                ],
                max_length=20,
            ),
        ),
    ]
