# Generated by Django 5.0.7 on 2024-07-25 14:30

from django.db import migrations

def create_ipac_kpi(apps, schema_editor):
    """
    Creates the new 'Índice de Productividad Ajustado por Calidad (IPAC)' KPI instance.
    """
    KPI = apps.get_model('employees', 'KPI')

    # A default target value. This can be adjusted by the administrator in the Django admin panel.
    # A higher IPAC score is better.
    default_target = 5.0

    KPI.objects.create(
        name='Índice de Productividad Ajustado por Calidad (IPAC)',
        description='Un KPI compuesto que mide la productividad (Nº de tareas) ponderada por la puntualidad y la calidad (tasa de error), dividida por el tiempo medio de ejecución. Un valor más alto es mejor.',
        measurement_type='composite_ipac',
        target_value=default_target
    )

def remove_ipac_kpi(apps, schema_editor):
    """
    Removes the IPAC KPI instance if the migration is reversed.
    """
    KPI = apps.get_model('employees', 'KPI')
    KPI.objects.filter(measurement_type='composite_ipac').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_add_ipac_kpi_choice_to_model'),
    ]

    operations = [
        migrations.RunPython(create_ipac_kpi, reverse_code=remove_ipac_kpi),
    ]
