# Generated by Django 5.2.6 on 2025-09-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_create_ipac_kpi_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("unfulfilled", "Unfulfilled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
