# Generated by Django 5.2.7 on 2025-10-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0012_task_status_alter_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
