# Generated by Django 5.2.7 on 2025-10-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_employee_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a custom favicon for the site.",
                        null=True,
                        upload_to="favicons/",
                    ),
                ),
            ],
        ),
    ]
