# Generated by Django 6.0.1 on 2026-01-29 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_task_recurrence_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DolibarrInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name, e.g., 'Empresa A'", max_length=255)),
                ('professional_id', models.CharField(help_text='ID Profesional 1 from Dolibarr Admin Panel', max_length=100, unique=True)),
                ('api_secret', models.CharField(help_text='Secret key for HMAC validation of webhooks', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sender_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='kpi',
            name='internal_code',
            field=models.SlugField(blank=True, help_text='System code for logic mapping (e.g. SALES_EFFECTIVENESS)', null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='min_volume_threshold',
            field=models.IntegerField(default=0, help_text='Minimum volume of records required to trigger this KPI (e.g. 10 proformas)'),
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('earns_commissions', models.BooleanField(default=False, help_text='If true, this profile is eligible for variable sales commissions.')),
                ('description', models.TextField(blank=True)),
                ('kpis', models.ManyToManyField(blank=True, related_name='job_profiles', to='employees.kpi')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Job Profile determining active KPIs for this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.jobprofile'),
        ),
        migrations.CreateModel(
            name='KPIBonusTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Value required to reach this tier.', max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='employees.kpi')),
            ],
            options={
                'ordering': ['threshold'],
            },
        ),
        migrations.CreateModel(
            name='DolibarrUserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolibarr_user_id', models.IntegerField(help_text='Numeric User ID in Dolibarr (rowid)')),
                ('dolibarr_login', models.CharField(blank=True, help_text='Login username in Dolibarr (reference only)', max_length=100, null=True)),
                ('dolibarr_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.dolibarrinstance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dolibarr_identities', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Dolibarr User Identities',
                'unique_together': {('dolibarr_instance', 'dolibarr_user_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolibarr_product_id', models.IntegerField()),
                ('product_ref', models.CharField(help_text='SKU/Ref of the product', max_length=255)),
                ('created_at', models.DateTimeField()),
                ('dolibarr_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.dolibarrinstance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'unique_together': {('dolibarr_instance', 'dolibarr_product_id')},
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolibarr_id', models.IntegerField(help_text='RowID of the object in Dolibarr')),
                ('dolibarr_ref', models.CharField(help_text='Reference (e.g., FA23-001)', max_length=100)),
                ('origin_proforma_id', models.IntegerField(blank=True, help_text='RowID of the proforma (if this is an invoice)', null=True)),
                ('status', models.CharField(choices=[('proforma', 'Proforma/Proposal'), ('invoiced', 'Facturado/Invoiced'), ('cancelled', 'Cancelado/Cancelled'), ('credit_note', 'Nota de Crédito/Credit Note')], max_length=20)),
                ('amount_untaxed', models.DecimalField(decimal_places=2, help_text='Base imponible (Total HT)', max_digits=12)),
                ('date', models.DateField(help_text='Date of validation or invoicing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dolibarr_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.dolibarrinstance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('dolibarr_instance', 'dolibarr_id', 'status')},
            },
        ),
    ]
