# Generated by Django 5.2.11 on 2026-02-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0016_dolibarrinstance_webhooklog_kpi_internal_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcreationlog",
            name="is_suspect_duplicate",
            field=models.BooleanField(
                default=False,
                help_text="Flagged if same SKU was already created this month (anti-fraud per FEASIBILITY_REPORT 3.2.C.4)",
            ),
        ),
    ]
