# Generated by Django 6.0.1 on 2026-03-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_productcreationlog_is_suspect_duplicate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-effective_date'], 'verbose_name_plural': 'Salaries'},
        ),
        migrations.AddField(
            model_name='salary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'effective_date')},
        ),
    ]
