# Generated by Django 6.0.1 on 2026-03-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_salary_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comision sobre ventas netas facturadas (ej: 5.00 = 5%)', max_digits=5),
        ),
    ]
