# Generated by Django 6.0.1 on 2026-03-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_add_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when invoice was paid (set by PAYMENT_CUSTOMER_CREATE webhook)', null=True),
        ),
    ]
