# Generated by Django 6.0.1 on 2026-03-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_add_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='origin_order_id',
            field=models.IntegerField(blank=True, help_text='RowID of the order', null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='origin_proforma_id',
            field=models.IntegerField(blank=True, help_text='RowID of the proforma', null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='status',
            field=models.CharField(choices=[('proforma', 'Proforma/Proposal'), ('order', 'Pedido/Order'), ('invoiced', 'Facturado/Invoiced'), ('cancelled', 'Cancelado/Cancelled'), ('credit_note', 'Nota de Crédito/Credit Note')], max_length=20),
        ),
    ]
