# Generated by Django 6.0.1 on 2026-03-14 23:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_add_order_status_and_origin_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comision sobre ventas netas facturadas (ej: 5.00 = 5%). Maximo 100%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='internal_code',
            field=models.SlugField(blank=True, choices=[('', '(ninguno — usa measurement_type)'), ('SALES_EFFECTIVENESS', 'SALES_EFFECTIVENESS — Conversión proformas→facturas'), ('PRODUCT_CREATION', 'PRODUCT_CREATION — Productos creados (excluye duplicados)')], help_text='Codigo interno que activa logica especial. Si esta vacio, se usa el measurement_type.', null=True),
        ),
    ]
