# Generated by Django 4.2.24 on 2026-03-14 22:59
#
# Recuperada del servidor de producción (2026-07-07): se generó allí y nunca
# se subió al repo, lo que causaba conflictos de "multiple leaf nodes" en
# cada release. Ya está aplicada en producción.

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_add_order_status_and_origin_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comision sobre ventas netas facturadas (ej: 5.00 = 5%). Maximo 100%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
