# Generated by Django 6.0.1 on 2026-03-21 17:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_kpi_internal_code_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running balance. Negative = debt to recover from future commissions.', max_digits=12)),
                ('last_computed_year', models.IntegerField(default=0)),
                ('last_computed_month', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_balance', to='employees.employee')),
            ],
        ),
    ]
