# Generated by Django 6.0.1 on 2026-03-21 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_commission_balance_and_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionbalance',
            name='pre_month_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Snapshot of balance BEFORE the current month's calculation. Used for idempotent recalculation.", max_digits=12),
        ),
    ]
