# Generated by Django 4.2.24 on 2026-03-21 17:10
#
# Recuperada del servidor de producción (2026-07-07). Merge vacío que une la
# rama 0022_alter_employee_commission_percentage (creada en el servidor) con
# la rama del repo. Ya está aplicada en producción.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_alter_employee_commission_percentage'),
        ('employees', '0023_commission_balance_and_fixes'),
    ]

    operations = [
    ]
