# Generated by Django 6.0.1 on 2026-07-07 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_audit_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descuenta_saldo', models.BooleanField(default=True, help_text='Si los días aprobados descuentan del saldo anual de vacaciones.')),
                ('es_remunerada', models.BooleanField(default=True, help_text='Si los días aprobados se pagan (generan WorkLog de 8 horas).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de ausencia',
                'verbose_name_plural': 'Tipos de ausencia',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='dias_vacaciones_anuales',
            field=models.PositiveSmallIntegerField(default=15, help_text='Días de vacaciones por año calendario que descuentan del saldo.'),
        ),
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_habiles', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('comentario_decision', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('decidida_en', models.DateTimeField(blank=True, null=True)),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_decididas', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ausencia', to='employees.employee')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.tipoausencia')),
            ],
            options={
                'verbose_name': 'Solicitud de ausencia',
                'verbose_name_plural': 'Solicitudes de ausencia',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='worklog',
            name='ausencia',
            field=models.ForeignKey(blank=True, help_text='Si el día proviene de una ausencia remunerada aprobada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='employees.solicitudausencia'),
        ),
        migrations.CreateModel(
            name='ReciboNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('datos', models.JSONField(help_text='Desglose completo de calculate_salary al momento de emisión.')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='employees.employee')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo de nómina',
                'verbose_name_plural': 'Recibos de nómina',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
