# Generated by Django 6.0.1 on 2026-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_tipos_ausencia_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Último aviso por email de vencimiento (idempotencia del cron diario).', null=True),
        ),
    ]
