# Generated by Django 6.0.1 on 2026-07-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_merge_0024_audit_fixes_0024_merge_20260321_1110'),
        ('employees', '0027_task_reminder_sent_at'),
    ]

    operations = [
    ]
