# Generated by Django 6.0.1 on 2026-07-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_merge_20260707_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolibarrinstance',
            name='api_base_url',
            field=models.URLField(blank=True, default='', help_text='URL raíz de Dolibarr, ej: https://erp.empresa.com (sin /api). Vacío = sin push de nómina.'),
        ),
        migrations.AddField(
            model_name='dolibarrinstance',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='DOLAPIKEY de un usuario Dolibarr con permiso salaries → write. Vacío = sin push de nómina.', max_length=128),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='dolibarr_error',
            field=models.TextField(blank=True, default='', help_text='Último error al intentar el envío a Dolibarr; vacío si OK o nunca intentado.'),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='dolibarr_salary_id',
            field=models.IntegerField(blank=True, help_text='rowid en llx_salary si el recibo ya fue enviado a Dolibarr.', null=True),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='dolibarr_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
