# Generated by Django 5.2.6 on 2025-09-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caldav", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="alarm_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Minutes before the event to trigger an alarm.",
                null=True,
            ),
        ),
    ]
