# Generated by Django 5.2.6 on 2025-09-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caldav", "0002_calendarevent_alarm_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="uid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
