# Generated by Django 6.0.1 on 2026-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caldav', '0003_calendarevent_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='raw_ical',
            field=models.TextField(blank=True, default='', help_text='Full RFC 5545 iCalendar content to preserve client-specific extensions like X-MOZ-LASTACK.'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
