# Generated by Django 6.0.1 on 2026-02-27 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0017_productcreationlog_is_suspect_duplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Perfil Estándar', max_length=100)),
                ('min_responsabilidad', models.FloatField(default=4.0, help_text='Conscientiousness mínimo (1-5)')),
                ('min_amabilidad', models.FloatField(default=3.0, help_text='Agreeableness mínimo (1-5)')),
                ('max_neuroticismo', models.FloatField(default=3.0, help_text='Neuroticism máximo (1-5)')),
                ('min_apertura', models.FloatField(default=2.5, help_text='Openness mínimo (1-5)')),
                ('min_extroversion', models.FloatField(default=2.0, help_text='Extraversion mínimo (1-5)')),
                ('min_compromiso_organizacional', models.FloatField(default=3.5, help_text='Allen & Meyer mínimo (1-5)')),
                ('min_obediencia', models.FloatField(default=3.5, help_text='Escala conformidad mínimo (1-5)')),
                ('min_memoria', models.FloatField(default=60.0, help_text='% mínimo en test de memoria')),
                ('min_matrices', models.FloatField(default=50.0, help_text='% mínimo en matrices (inteligencia)')),
                ('min_situacional', models.FloatField(default=60.0, help_text='% mínimo en prueba situacional')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil Objetivo',
                'verbose_name_plural': 'Perfiles Objetivo',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo_escala', models.CharField(choices=[('LIKERT5', 'Likert 1-5'), ('LIKERT7', 'Likert 1-7'), ('OPCION_MULTIPLE', 'Opción múltiple'), ('TEXTO_LIBRE', 'Texto libre (frases incompletas)'), ('SECUENCIA', 'Secuencia (memoria)'), ('SELECCION_COLOR', 'Selección de color')], max_length=20)),
                ('dimension', models.CharField(choices=[('BF_RESP', 'Big Five: Responsabilidad'), ('BF_AMAB', 'Big Five: Amabilidad'), ('BF_NEUR', 'Big Five: Neuroticismo'), ('BF_APER', 'Big Five: Apertura'), ('BF_EXTR', 'Big Five: Extroversión'), ('CO_AFEC', 'Compromiso: Afectivo'), ('CO_CONT', 'Compromiso: Continuidad'), ('CO_NORM', 'Compromiso: Normativo'), ('OB_DISC', 'Obediencia: Disciplina'), ('OB_CONF', 'Obediencia: Conformidad normativa'), ('OB_AUTO', 'Obediencia: Orientación a autoridad'), ('SIT_RESP', 'Situacional: Responsabilidad'), ('SIT_OBED', 'Situacional: Obediencia'), ('SIT_LEAL', 'Situacional: Lealtad'), ('FR_TRAB', 'Frases: Actitud hacia el trabajo'), ('FR_AUTO', 'Frases: Actitud hacia la autoridad'), ('FR_COMP', 'Frases: Compromiso personal'), ('COL_PREF', 'Colores: Preferencia'), ('GENERAL', 'General')], default='GENERAL', max_length=10)),
                ('es_inversa', models.BooleanField(default=False, help_text='Si True, puntaje se invierte (6 - valor)')),
                ('orden', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, help_text='Para matrices progresivas', null=True, upload_to='psicoevaluacion/preguntas/')),
                ('secuencia_correcta', models.JSONField(blank=True, help_text='Para memoria: [3,7,2,9,1] secuencia a recordar', null=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'ordering': ['prueba', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BIGFIVE', 'Big Five (OCEAN)'), ('COMPROMISO', 'Compromiso Organizacional (Allen & Meyer)'), ('OBEDIENCIA', 'Escala de Obediencia/Conformidad'), ('MEMORIA', 'Test de Memoria de Trabajo'), ('MATRICES', 'Matrices Progresivas'), ('ARBOL', 'Test del Árbol (Koch)'), ('PERSONA_LLUVIA', 'Persona bajo la Lluvia'), ('FRASES', 'Frases Incompletas (Sacks)'), ('COLORES', 'Test de Colores (Lüscher)'), ('SITUACIONAL', 'Prueba Situacional')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(help_text='Texto que verá el candidato antes de iniciar')),
                ('tiempo_limite_minutos', models.IntegerField(blank=True, help_text='Nulo = sin límite', null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de presentación')),
                ('activa', models.BooleanField(default=True)),
                ('es_proyectiva', models.BooleanField(default=False, help_text='True si requiere revisión manual')),
            ],
            options={
                'verbose_name': 'Prueba',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('valor', models.IntegerField(help_text='Valor numérico de esta opción')),
                ('imagen', models.ImageField(blank=True, help_text='Para opciones visuales (matrices, colores)', null=True, upload_to='psicoevaluacion/opciones/')),
                ('orden', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='psicoevaluacion.pregunta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='psicoevaluacion.prueba'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(editable=False, help_text='Token para URL de acceso', max_length=64, unique=True)),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres completos')),
                ('cedula', models.CharField(max_length=13, verbose_name='Número de cédula')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cargo_postulado', models.CharField(blank=True, max_length=200, verbose_name='Cargo al que postula')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente - Link generado'), ('EN_CURSO', 'En curso - Candidato realizando pruebas'), ('COMPLETADA', 'Completada - Pendiente revisión'), ('REVISADA', 'Revisada - Con resultados finales'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(help_text='Después de esta fecha el link deja de funcionar')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Cuando el candidato comenzó la evaluación', null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('ip_acceso', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('notas_evaluador', models.TextField(blank=True, verbose_name='Notas del evaluador')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, help_text='Si ya existe como empleado en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('perfil_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psicoevaluacion.perfilobjetivo')),
                ('prueba_actual', models.ForeignKey(blank=True, help_text='Última prueba en la que está el candidato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='psicoevaluacion.prueba')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('tiempo_respuesta_seg', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_matrices', to='psicoevaluacion.evaluacion')),
                ('opcion_seleccionada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psicoevaluacion.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicoevaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Matriz',
            },
        ),
        migrations.CreateModel(
            name='RespuestaMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia_presentada', models.JSONField(help_text='Secuencia que se le mostró')),
                ('secuencia_respondida', models.JSONField(help_text='Secuencia que el candidato ingresó')),
                ('es_correcta', models.BooleanField(default=False)),
                ('longitud_secuencia', models.IntegerField(help_text='Largo de la secuencia (dificultad)')),
                ('tiempo_respuesta_seg', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_memoria', to='psicoevaluacion.evaluacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicoevaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Memoria',
            },
        ),
        migrations.CreateModel(
            name='RespuestaProyectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIBUJO', 'Dibujo en canvas'), ('TEXTO', 'Texto libre (frases incompletas)')], max_length=10)),
                ('imagen_canvas', models.TextField(blank=True, help_text='Base64 del dibujo en canvas')),
                ('datos_trazo', models.JSONField(blank=True, help_text='Datos de trazos: coordenadas, presión, velocidad, orden', null=True)),
                ('texto_respuesta', models.TextField(blank=True)),
                ('puntuacion_manual', models.IntegerField(blank=True, help_text='Puntuación asignada manualmente (1-10)', null=True)),
                ('observaciones_evaluador', models.TextField(blank=True)),
                ('revisado', models.BooleanField(default=False)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total_seg', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_proyectivas', to='psicoevaluacion.evaluacion')),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psicoevaluacion.pregunta')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicoevaluacion.prueba')),
            ],
            options={
                'verbose_name': 'Respuesta Proyectiva',
            },
        ),
        migrations.CreateModel(
            name='RespuestaSituacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('justificacion', models.TextField(blank=True, help_text='Texto opcional del candidato explicando su elección')),
                ('tiempo_respuesta_seg', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_situacionales', to='psicoevaluacion.evaluacion')),
                ('opcion_seleccionada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psicoevaluacion.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicoevaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta Situacional',
            },
        ),
        migrations.CreateModel(
            name='ResultadoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_responsabilidad', models.FloatField(null=True)),
                ('puntaje_amabilidad', models.FloatField(null=True)),
                ('puntaje_neuroticismo', models.FloatField(null=True)),
                ('puntaje_apertura', models.FloatField(null=True)),
                ('puntaje_extroversion', models.FloatField(null=True)),
                ('puntaje_compromiso_afectivo', models.FloatField(null=True)),
                ('puntaje_compromiso_continuidad', models.FloatField(null=True)),
                ('puntaje_compromiso_normativo', models.FloatField(null=True)),
                ('puntaje_compromiso_total', models.FloatField(null=True)),
                ('puntaje_obediencia', models.FloatField(null=True)),
                ('puntaje_memoria', models.FloatField(help_text='Porcentaje de aciertos', null=True)),
                ('max_secuencia_memoria', models.IntegerField(help_text='Longitud máxima de secuencia recordada', null=True)),
                ('puntaje_matrices', models.FloatField(help_text='Porcentaje de aciertos', null=True)),
                ('puntaje_situacional', models.FloatField(null=True)),
                ('puntaje_arbol', models.FloatField(null=True)),
                ('puntaje_persona_lluvia', models.FloatField(null=True)),
                ('puntaje_frases', models.FloatField(null=True)),
                ('puntaje_colores', models.JSONField(blank=True, help_text='Interpretación de secuencia de colores', null=True)),
                ('indice_responsabilidad_total', models.FloatField(help_text='Índice ponderado combinando Big Five + situacional', null=True)),
                ('indice_lealtad', models.FloatField(help_text='Índice ponderado de compromiso + situacional lealtad', null=True)),
                ('indice_obediencia_total', models.FloatField(help_text='Índice combinado obediencia + situacional', null=True)),
                ('veredicto_automatico', models.CharField(choices=[('APTO', 'APTO'), ('NO_APTO', 'NO APTO'), ('REVISION', 'Requiere revisión adicional')], default='REVISION', max_length=10)),
                ('veredicto_manual', models.CharField(blank=True, choices=[('APTO', 'APTO'), ('NO_APTO', 'NO APTO'), ('REVISION', 'Requiere revisión adicional')], max_length=10, null=True)),
                ('veredicto_final', models.CharField(blank=True, choices=[('APTO', 'APTO'), ('NO_APTO', 'NO APTO'), ('REVISION', 'Requiere revisión adicional')], help_text='El evaluador puede sobrescribir el veredicto automático', max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='psicoevaluacion.evaluacion')),
            ],
            options={
                'verbose_name': 'Resultado Final',
                'verbose_name_plural': 'Resultados Finales',
            },
        ),
        migrations.CreateModel(
            name='RespuestaPsicometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(help_text='Valor numérico seleccionado')),
                ('tiempo_respuesta_seg', models.IntegerField(blank=True, help_text='Segundos que tardó en responder', null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_psicometricas', to='psicoevaluacion.evaluacion')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psicoevaluacion.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicoevaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta Psicométrica',
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
    ]
