# Generated by Django 6.0.1 on 2026-02-27 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_seleccionadas',
            field=models.JSONField(blank=True, help_text='IDs de preguntas seleccionadas para esta evaluación', null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='par_consistencia',
            field=models.ForeignKey(blank=True, help_text='Par duplicado para control de consistencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='par_vinculado', to='psicoevaluacion.pregunta'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='items_a_aplicar',
            field=models.IntegerField(default=0, help_text='Preguntas a seleccionar por evaluación (0 = aplicar todas)'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='items_banco',
            field=models.IntegerField(default=0, help_text='Total de preguntas disponibles en el banco'),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='evaluacion_confiable',
            field=models.BooleanField(default=True, help_text='False si deseabilidad alta o consistencia baja'),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='indice_consistencia',
            field=models.FloatField(blank=True, help_text='Concordancia entre pares duplicados (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_deseabilidad_social',
            field=models.FloatField(blank=True, help_text='Promedio escala deseabilidad social (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='dimension',
            field=models.CharField(choices=[('BF_RESP', 'Big Five: Responsabilidad'), ('BF_AMAB', 'Big Five: Amabilidad'), ('BF_NEUR', 'Big Five: Neuroticismo'), ('BF_APER', 'Big Five: Apertura'), ('BF_EXTR', 'Big Five: Extroversión'), ('CO_AFEC', 'Compromiso: Afectivo'), ('CO_CONT', 'Compromiso: Continuidad'), ('CO_NORM', 'Compromiso: Normativo'), ('OB_DISC', 'Obediencia: Disciplina'), ('OB_CONF', 'Obediencia: Conformidad normativa'), ('OB_AUTO', 'Obediencia: Orientación a autoridad'), ('SIT_RESP', 'Situacional: Responsabilidad'), ('SIT_OBED', 'Situacional: Obediencia'), ('SIT_LEAL', 'Situacional: Lealtad'), ('FR_TRAB', 'Frases: Actitud hacia el trabajo'), ('FR_AUTO', 'Frases: Actitud hacia la autoridad'), ('FR_COMP', 'Frases: Compromiso personal'), ('COL_PREF', 'Colores: Preferencia'), ('DS_DESB', 'Deseabilidad Social'), ('GENERAL', 'General')], default='GENERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='tipo',
            field=models.CharField(choices=[('BIGFIVE', 'Big Five (OCEAN)'), ('COMPROMISO', 'Compromiso Organizacional (Allen & Meyer)'), ('OBEDIENCIA', 'Escala de Obediencia/Conformidad'), ('MEMORIA', 'Test de Memoria de Trabajo'), ('MATRICES', 'Matrices Progresivas'), ('ARBOL', 'Test del Árbol (Koch)'), ('PERSONA_LLUVIA', 'Persona bajo la Lluvia'), ('FRASES', 'Frases Incompletas (Sacks)'), ('COLORES', 'Test de Colores (Lüscher)'), ('SITUACIONAL', 'Prueba Situacional'), ('DESEABILIDAD', 'Escala de Deseabilidad Social')], max_length=20, unique=True),
        ),
    ]
