# Generated by Django 6.0.1 on 2026-02-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0002_evaluacion_preguntas_seleccionadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_activo', models.CharField(choices=[('ANTHROPIC', 'Anthropic (Claude)'), ('GOOGLE', 'Google (Gemini)')], default='ANTHROPIC', max_length=10)),
                ('anthropic_api_key', models.CharField(blank=True, help_text='API key de Anthropic', max_length=200)),
                ('anthropic_model', models.CharField(default='claude-sonnet-4-20250514', help_text='Modelo Anthropic a usar', max_length=100)),
                ('google_api_key', models.CharField(blank=True, help_text='API key de Google AI', max_length=200)),
                ('google_model', models.CharField(default='gemini-2.0-flash', help_text='Modelo Gemini a usar', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración IA',
                'verbose_name_plural': 'Configuración IA',
            },
        ),
        migrations.AddField(
            model_name='perfilobjetivo',
            name='metodo_veredicto',
            field=models.CharField(choices=[('CONTEO_FALLOS', 'Conteo de fallos (0=APTO, 1=REVISIÓN, 2+=NO APTO)'), ('ESTRICTO', 'Estricto (cualquier fallo = NO APTO)')], default='CONTEO_FALLOS', help_text='Método para determinar el veredicto automático', max_length=15),
        ),
    ]
