# Generated by Django 6.0.1 on 2026-02-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0003_configuracionia_perfilobjetivo_metodo_veredicto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilobjetivo',
            name='min_atencion_detalle',
            field=models.FloatField(default=60.0, help_text='% mínimo en atención al detalle'),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_atencion_comparacion',
            field=models.FloatField(blank=True, help_text='F1 score comparación de documentos (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_atencion_detalle',
            field=models.FloatField(blank=True, help_text='Puntaje compuesto atención al detalle (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_atencion_secuencias',
            field=models.FloatField(blank=True, help_text='% aciertos en secuencias con error (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_atencion_verificacion',
            field=models.FloatField(blank=True, help_text='% aciertos verificación de datos (0-100%)', null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='dimension',
            field=models.CharField(choices=[('BF_RESP', 'Big Five: Responsabilidad'), ('BF_AMAB', 'Big Five: Amabilidad'), ('BF_NEUR', 'Big Five: Neuroticismo'), ('BF_APER', 'Big Five: Apertura'), ('BF_EXTR', 'Big Five: Extroversión'), ('CO_AFEC', 'Compromiso: Afectivo'), ('CO_CONT', 'Compromiso: Continuidad'), ('CO_NORM', 'Compromiso: Normativo'), ('OB_DISC', 'Obediencia: Disciplina'), ('OB_CONF', 'Obediencia: Conformidad normativa'), ('OB_AUTO', 'Obediencia: Orientación a autoridad'), ('SIT_RESP', 'Situacional: Responsabilidad'), ('SIT_OBED', 'Situacional: Obediencia'), ('SIT_LEAL', 'Situacional: Lealtad'), ('FR_TRAB', 'Frases: Actitud hacia el trabajo'), ('FR_AUTO', 'Frases: Actitud hacia la autoridad'), ('FR_COMP', 'Frases: Compromiso personal'), ('COL_PREF', 'Colores: Preferencia'), ('DS_DESB', 'Deseabilidad Social'), ('AT_COMP', 'Atención: Comparación de documentos'), ('AT_VERI', 'Atención: Verificación de datos'), ('AT_SECU', 'Atención: Secuencias con error'), ('GENERAL', 'General')], default='GENERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='tipo',
            field=models.CharField(choices=[('BIGFIVE', 'Big Five (OCEAN)'), ('COMPROMISO', 'Compromiso Organizacional (Allen & Meyer)'), ('OBEDIENCIA', 'Escala de Obediencia/Conformidad'), ('MEMORIA', 'Test de Memoria de Trabajo'), ('MATRICES', 'Matrices Progresivas'), ('ARBOL', 'Test del Árbol (Koch)'), ('PERSONA_LLUVIA', 'Persona bajo la Lluvia'), ('FRASES', 'Frases Incompletas (Sacks)'), ('COLORES', 'Test de Colores (Lüscher)'), ('SITUACIONAL', 'Prueba Situacional'), ('DESEABILIDAD', 'Escala de Deseabilidad Social'), ('ATENCION', 'Atención al Detalle')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='RespuestaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtipo', models.CharField(choices=[('COMPARACION', 'Comparación de documentos'), ('VERIFICACION', 'Verificación de datos cruzados'), ('SECUENCIA', 'Secuencias con error')], max_length=15)),
                ('respuesta_json', models.JSONField(blank=True, help_text='Respuesta estructurada del candidato', null=True)),
                ('es_correcta', models.BooleanField(default=False, help_text='True si la respuesta es completamente correcta')),
                ('puntaje_parcial', models.FloatField(default=0, help_text='Puntaje parcial (0-1) para respuestas parcialmente correctas')),
                ('tiempo_respuesta_seg', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_atencion', to='psicoevaluacion.evaluacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicoevaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta Atención al Detalle',
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
    ]
