# Generated by Django 6.0.1 on 2026-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0004_atencion_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilobjetivo',
            name='min_memoria_visual',
            field=models.FloatField(default=60.0, help_text='% mínimo en memoria visual (score combinado)'),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_memoria_visual',
            field=models.FloatField(blank=True, help_text='Score combinado memoria visual (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_mv_honestidad',
            field=models.FloatField(blank=True, help_text='Aciertos preguntas trampa (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_mv_precision',
            field=models.FloatField(blank=True, help_text='Aciertos preguntas reales (0-100%)', null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='dimension',
            field=models.CharField(choices=[('BF_RESP', 'Big Five: Responsabilidad'), ('BF_AMAB', 'Big Five: Amabilidad'), ('BF_NEUR', 'Big Five: Neuroticismo'), ('BF_APER', 'Big Five: Apertura'), ('BF_EXTR', 'Big Five: Extroversión'), ('CO_AFEC', 'Compromiso: Afectivo'), ('CO_CONT', 'Compromiso: Continuidad'), ('CO_NORM', 'Compromiso: Normativo'), ('OB_DISC', 'Obediencia: Disciplina'), ('OB_CONF', 'Obediencia: Conformidad normativa'), ('OB_AUTO', 'Obediencia: Orientación a autoridad'), ('SIT_RESP', 'Situacional: Responsabilidad'), ('SIT_OBED', 'Situacional: Obediencia'), ('SIT_LEAL', 'Situacional: Lealtad'), ('FR_TRAB', 'Frases: Actitud hacia el trabajo'), ('FR_AUTO', 'Frases: Actitud hacia la autoridad'), ('FR_COMP', 'Frases: Compromiso personal'), ('COL_PREF', 'Colores: Preferencia'), ('DS_DESB', 'Deseabilidad Social'), ('AT_COMP', 'Atención: Comparación de documentos'), ('AT_VERI', 'Atención: Verificación de datos'), ('AT_SECU', 'Atención: Secuencias con error'), ('MV_A_REAL', 'Memoria Visual A: Real'), ('MV_A_TRAP', 'Memoria Visual A: Trampa'), ('MV_B_REAL', 'Memoria Visual B: Real'), ('MV_B_TRAP', 'Memoria Visual B: Trampa'), ('MV_C_REAL', 'Memoria Visual C: Real'), ('MV_C_TRAP', 'Memoria Visual C: Trampa'), ('GENERAL', 'General')], default='GENERAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='tipo',
            field=models.CharField(choices=[('BIGFIVE', 'Big Five (OCEAN)'), ('COMPROMISO', 'Compromiso Organizacional (Allen & Meyer)'), ('OBEDIENCIA', 'Escala de Obediencia/Conformidad'), ('MEMORIA', 'Test de Memoria de Trabajo'), ('MATRICES', 'Matrices Progresivas'), ('ARBOL', 'Test del Árbol (Koch)'), ('PERSONA_LLUVIA', 'Persona bajo la Lluvia'), ('FRASES', 'Frases Incompletas (Sacks)'), ('COLORES', 'Test de Colores (Lüscher)'), ('SITUACIONAL', 'Prueba Situacional'), ('DESEABILIDAD', 'Escala de Deseabilidad Social'), ('ATENCION', 'Atención al Detalle'), ('MEMORIA_VISUAL', 'Memoria Visual')], max_length=20, unique=True),
        ),
    ]
