# Generated by Django 6.0.1 on 2026-05-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0005_memoria_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_frases_autoridad',
            field=models.FloatField(blank=True, help_text='Frases: Relación con la autoridad (FR_AUTO, 1-10)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_frases_compromiso',
            field=models.FloatField(blank=True, help_text='Frases: Compromiso organizacional (FR_COMP, 1-10)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='puntaje_frases_trabajo',
            field=models.FloatField(blank=True, help_text='Frases: Actitud hacia el trabajo (FR_TRAB, 1-10)', null=True),
        ),
        migrations.AlterField(
            model_name='resultadofinal',
            name='puntaje_frases',
            field=models.FloatField(help_text='Promedio general de Frases Incompletas (1-10)', null=True),
        ),
    ]
