# Generated by Django 6.0.1 on 2026-05-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0006_resultadofinal_puntaje_frases_autoridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadofinal',
            name='detalle_arbol',
            field=models.JSONField(blank=True, help_text='Sub-indicadores del Test del Árbol (rúbrica desglosada)', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='detalle_colores',
            field=models.JSONField(blank=True, help_text='Sub-indicadores del Test de Colores Lüscher', null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='detalle_persona_lluvia',
            field=models.JSONField(blank=True, help_text='Sub-indicadores de Persona Bajo la Lluvia', null=True),
        ),
    ]
