# Generated by Django 6.0.1 on 2026-05-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0008_memoria_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadofinal',
            name='veredicto_automatico',
            field=models.CharField(choices=[('APTO', 'APTO'), ('NO_APTO', 'NO APTO'), ('REVISION', 'Requiere revisión adicional'), ('PENDIENTE', 'Pendiente - Sin perfil asignado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='resultadofinal',
            name='veredicto_final',
            field=models.CharField(blank=True, choices=[('APTO', 'APTO'), ('NO_APTO', 'NO APTO'), ('REVISION', 'Requiere revisión adicional'), ('PENDIENTE', 'Pendiente - Sin perfil asignado')], help_text='El evaluador puede sobrescribir el veredicto automático', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultadofinal',
            name='veredicto_manual',
            field=models.CharField(blank=True, choices=[('APTO', 'APTO'), ('NO_APTO', 'NO APTO'), ('REVISION', 'Requiere revisión adicional'), ('PENDIENTE', 'Pendiente - Sin perfil asignado')], max_length=10, null=True),
        ),
    ]
