# Generated by Django 6.0.1 on 2026-05-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0009_alter_resultadofinal_veredicto_automatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadofinal',
            name='detalle_veredicto',
            field=models.JSONField(blank=True, help_text='Desglose por indicador: puntaje vs umbral del perfil y estado (OK / FALLO / SIN_DATO). Explica por qué se emitió el veredicto.', null=True),
        ),
    ]
