# Generated by Django 6.0.1 on 2026-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoevaluacion', '0010_resultadofinal_detalle_veredicto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='link_enviado_en',
            field=models.DateTimeField(blank=True, help_text='Último envío del link de la evaluación al correo del candidato', null=True),
        ),
    ]
